
package gov.usda.fsa.fcao.flpids.fbpservice.jaxws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebService(name = "FBPServiceSoap", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI)
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FBPServiceSoap {


    /**
     *
     * @param username
     * @param coreCustomerID
     * @param passwordText
     * @param sitename
     * @param passwordDigest
     * @return
     *     returns gov.usda.fsa.fcao.flpids.fbpservice.jaxws.GetDALRDataResult
     */
    @WebMethod(operationName = "GetDALRData", action = FBPWsdlInfo.FBP_NAMESPACE_URI+"GetDALRData")
    @WebResult(name = "GetDALRDataResult", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "GetDALRDataResult")
    public GetDALRDataResult getDALRData(
        @WebParam(name = "sitename", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "sitename")
        String sitename,
        @WebParam(name = "username", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "username")
        String username,
        @WebParam(name = "passwordText", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "passwordText")
        String passwordText,
        @WebParam(name = "passwordDigest", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "passwordDigest")
        String passwordDigest,
        @WebParam(name = "coreCustomerID", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "coreCustomerID")
        Integer coreCustomerID);

    /**
     *
     * @param username
     * @param coreCustomerID
     * @param passwordText
     * @param sitename
     * @param passwordDigest
     * @return
     *     returns gov.usda.fsa.fcao.flpids.fbpservice.jaxws.GetDLMDataResult
     */
    @WebMethod(operationName = "GetDLMData", action = FBPWsdlInfo.FBP_NAMESPACE_URI+"GetDLMData")
    @WebResult(name = "GetDLMDataResult", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "GetDLMDataResult")
    public GetDLMDataResult getDLMData(
        @WebParam(name = "sitename", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "sitename")
        String sitename,
        @WebParam(name = "username", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "username")
        String username,
        @WebParam(name = "passwordText", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "passwordText")
        String passwordText,
        @WebParam(name = "passwordDigest", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "passwordDigest")
        String passwordDigest,
        @WebParam(name = "coreCustomerID", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "coreCustomerID")
        Integer coreCustomerID);

    /**
     *
     * @param username
     * @param coreCustomerID
     * @param passwordText
     * @param sitename
     * @param passwordDigest
     * @return
     *     returns gov.usda.fsa.fcao.flpids.fbpservice.jaxws.GetDLMYEADataResult
     */
    @WebMethod(operationName = "GetDLMYEAData", action = FBPWsdlInfo.FBP_NAMESPACE_URI+"GetDLMYEAData")
    @WebResult(name = "GetDLMYEADataResult", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "GetDLMYEADataResult")
    public GetDLMYEADataResult getDLMYEAData(
        @WebParam(name = "sitename", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "sitename")
        String sitename,
        @WebParam(name = "username", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "username")
        String username,
        @WebParam(name = "passwordText", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "passwordText")
        String passwordText,
        @WebParam(name = "passwordDigest", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "passwordDigest")
        String passwordDigest,
        @WebParam(name = "coreCustomerID", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "coreCustomerID")
        Integer coreCustomerID);

    
    /**
    *
    * @param username
    * @param coreCustomerID
    * @param passwordText
    * @param sitename
    * @param passwordDigest
    * @return
    *     returns gov.usda.fsa.fcao.flpids.fbpservice.jaxws.GetLenderStaffDataResult
    */
   @WebMethod(operationName = "GetLenderStaffData", action = FBPWsdlInfo.FBP_NAMESPACE_URI+"GetLenderStaffData")
   @WebResult(name = "GetLenderStaffDataResult", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "GetLenderStaffDataResult")
   public GetLenderStaffDataResult getLenderStaffData(
       @WebParam(name = "sitename", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "sitename")
       String sitename,
       @WebParam(name = "username", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "username")
       String username,
       @WebParam(name = "passwordText", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "passwordText")
       String passwordText,
       @WebParam(name = "passwordDigest", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "passwordDigest")
       String passwordDigest,
       @WebParam(name = "coreCustomerIDs", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "coreCustomerIDs")
       ArrayOfInt coreCustomerIDs);
    
    /**
     *
     * @param username
     * @param passwordText
     * @param passwordDigest
     * @return
     *     returns gov.usda.fsa.fcao.flpids.fbpservice.jaxws.GetFLPRALoanServicingDataResult
     */
    @WebMethod(operationName = "GetFLPRALoanServicingData", action = FBPWsdlInfo.FBP_NAMESPACE_URI+"GetFLPRALoanServicingData")
    @WebResult(name = "GetFLPRALoanServicingDataResult", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "GetFLPRALoanServicingDataResult")
    public GetFLPRALoanServicingDataResult getFLPRALoanServicingData(
        @WebParam(name = "username", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "username")
        String username,
        @WebParam(name = "passwordText", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "passwordText")
        String passwordText,
        @WebParam(name = "passwordDigest", targetNamespace = FBPWsdlInfo.FBP_NAMESPACE_URI, partName = "passwordDigest")
        String passwordDigest);

}
